/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculadorapapel;

import java.awt.Font;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import static java.sql.DriverManager.println;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Grupo Francisco Nicolau, Victor Muñoz, Adrian Amoros, Mar López
 */
public class CalculadoraPapel1 extends javax.swing.JFrame {
    //Declaraciones
        private float auxfloat1, auxfloat2;
        private float memoria;
	private char auxOperacion;
        private String auxPantalla;
        private String ruta="src\\registroCalculadora.txt";                   //Ruta donde se guardará nuestro documento.
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yy");  //Fecha
        String fecha = sdf.format(new Date());  //Fecha almacenada en String.
        /*public Font negrita = new Font("Arial", Font.BOLD, 14);
        public Font font1= new Font ("Arial",Font.PLAIN,12);*/
        
        


    /** Creates new form CalculadoraPapel1 */
    public CalculadoraPapel1() {
                
        initComponents();
        
          /*Método redimensionar boton*/
        ImageIcon icon = new ImageIcon("src\\calculadorapapel\\Guardar.jpg");
        Image imgGuardar = icon.getImage(); //convertimos icon en una imagen
        Image otraimgGuardar = imgGuardar.getScaledInstance(50,50,java.awt.Image.SCALE_SMOOTH); //creamos una imagen nueva dándole las dimensiones que queramos a la antigua
        ImageIcon otroicon = new ImageIcon(otraimgGuardar);
        jB_guardarTXT.setIcon(otroicon);
        
        ImageIcon icon2 = new ImageIcon("src\\calculadorapapel\\Abrir.jpg");
        Image imgAbrir = icon2.getImage(); //convertimos icon en una imagen
        Image otraimgAbrir = imgAbrir.getScaledInstance(50,50,java.awt.Image.SCALE_SMOOTH); //creamos una imagen nueva dándole las dimensiones que queramos a la antigua
        ImageIcon otroicon2 = new ImageIcon(otraimgAbrir);
        jB_cargarTXT.setIcon(otroicon2);
        
        ImageIcon icon3 = new ImageIcon("src\\calculadorapapel\\text.jpg");
        Image imgText = icon3.getImage(); //convertimos icon en una imagen
        Image otraimgText = imgText.getScaledInstance(50,50,java.awt.Image.SCALE_SMOOTH); //creamos una imagen nueva dándole las dimensiones que queramos a la antigua
        ImageIcon otroicon3 = new ImageIcon(otraimgText);
        jB_Visualizar.setIcon(otroicon3);
        
        ImageIcon icon4 = new ImageIcon("src\\calculadorapapel\\borrar.jpg");
        Image imgBorrar = icon4.getImage(); //convertimos icon en una imagen
        Image otraimgBorrar = imgBorrar.getScaledInstance(50,50,java.awt.Image.SCALE_SMOOTH); //creamos una imagen nueva dándole las dimensiones que queramos a la antigua
        ImageIcon otroicon4 = new ImageIcon(otraimgBorrar);
        jB_Borrar.setIcon(otroicon4);
        
       
        
        
        this.setLocationRelativeTo(null);  
        pantallaPapel.setText(pantallaPapel.getText()+fecha+"\n\n");
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTF_Pantalla = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pantallaPapel = new javax.swing.JTextArea();
        jB_Back = new javax.swing.JButton();
        jB_CE = new javax.swing.JButton();
        jB_C = new javax.swing.JButton();
        jB_MC = new javax.swing.JButton();
        jB_MR = new javax.swing.JButton();
        jB_MS = new javax.swing.JButton();
        jB_Mmenos = new javax.swing.JButton();
        jB_Mmas = new javax.swing.JButton();
        jB_0 = new javax.swing.JButton();
        jB_00 = new javax.swing.JButton();
        jB_000 = new javax.swing.JButton();
        jB_1 = new javax.swing.JButton();
        jB_2 = new javax.swing.JButton();
        jB_3 = new javax.swing.JButton();
        jB_4 = new javax.swing.JButton();
        jB_5 = new javax.swing.JButton();
        jB_6 = new javax.swing.JButton();
        jB_7 = new javax.swing.JButton();
        jB_8 = new javax.swing.JButton();
        jB_9 = new javax.swing.JButton();
        jB_Punto = new javax.swing.JButton();
        jB_Sumar = new javax.swing.JButton();
        jB_Restar = new javax.swing.JButton();
        jB_Multiplicar = new javax.swing.JButton();
        jB_Dividir = new javax.swing.JButton();
        jB_Tantoporcien = new javax.swing.JButton();
        jB_UnoentreX = new javax.swing.JButton();
        jB_Mas_menos = new javax.swing.JButton();
        jB_Igual = new javax.swing.JButton();
        jB_guardarTXT = new javax.swing.JButton();
        jB_3ptos = new javax.swing.JButton();
        jTF_rutaOrigen = new javax.swing.JTextField();
        jB_cargarTXT = new javax.swing.JButton();
        jB_Visualizar = new javax.swing.JButton();
        jB_Borrar = new javax.swing.JButton();
        jB_cargarTXT1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jTF_Pantalla.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTF_Pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_Pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_PantallaActionPerformed(evt);
            }
        });

        pantallaPapel.setColumns(20);
        pantallaPapel.setRows(5);
        pantallaPapel.setWrapStyleWord(true);
        jScrollPane2.setViewportView(pantallaPapel);

        jB_Back.setBackground(new java.awt.Color(102, 102, 102));
        jB_Back.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_Back.setText("Back");
        jB_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_BackActionPerformed(evt);
            }
        });

        jB_CE.setBackground(new java.awt.Color(102, 102, 102));
        jB_CE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_CE.setText("CE");
        jB_CE.setRolloverEnabled(false);
        jB_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CEActionPerformed(evt);
            }
        });

        jB_C.setBackground(new java.awt.Color(102, 102, 102));
        jB_C.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_C.setText("C");
        jB_C.setToolTipText("");
        jB_C.setPreferredSize(new java.awt.Dimension(85, 50));
        jB_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CActionPerformed(evt);
            }
        });

        jB_MC.setBackground(new java.awt.Color(102, 102, 102));
        jB_MC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_MC.setText("MC");
        jB_MC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MCActionPerformed(evt);
            }
        });

        jB_MR.setBackground(new java.awt.Color(102, 102, 102));
        jB_MR.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_MR.setText("MR");
        jB_MR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MRActionPerformed(evt);
            }
        });

        jB_MS.setBackground(new java.awt.Color(102, 102, 102));
        jB_MS.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_MS.setText("MS");
        jB_MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MSActionPerformed(evt);
            }
        });

        jB_Mmenos.setBackground(new java.awt.Color(102, 102, 102));
        jB_Mmenos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_Mmenos.setText("M-");
        jB_Mmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MmenosActionPerformed(evt);
            }
        });

        jB_Mmas.setBackground(new java.awt.Color(102, 102, 102));
        jB_Mmas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_Mmas.setText("M+");
        jB_Mmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MmasActionPerformed(evt);
            }
        });

        jB_0.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_0.setText("0");
        jB_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0ActionPerformed(evt);
            }
        });

        jB_00.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_00.setText("00");
        jB_00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_00ActionPerformed(evt);
            }
        });

        jB_000.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_000.setText("000");
        jB_000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_000ActionPerformed(evt);
            }
        });

        jB_1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_1.setText("1");
        jB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1ActionPerformed(evt);
            }
        });

        jB_2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_2.setText("2");
        jB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2ActionPerformed(evt);
            }
        });

        jB_3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_3.setText("3");
        jB_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_3ActionPerformed(evt);
            }
        });

        jB_4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_4.setText("4");
        jB_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_4ActionPerformed(evt);
            }
        });

        jB_5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_5.setText("5");
        jB_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_5ActionPerformed(evt);
            }
        });

        jB_6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_6.setText("6");
        jB_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_6ActionPerformed(evt);
            }
        });

        jB_7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_7.setText("7");
        jB_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_7ActionPerformed(evt);
            }
        });

        jB_8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_8.setText("8");
        jB_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_8ActionPerformed(evt);
            }
        });

        jB_9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_9.setText("9");
        jB_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_9ActionPerformed(evt);
            }
        });

        jB_Punto.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_Punto.setText(".");
        jB_Punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_PuntoActionPerformed(evt);
            }
        });

        jB_Sumar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_Sumar.setText("+");
        jB_Sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SumarActionPerformed(evt);
            }
        });

        jB_Restar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_Restar.setText("-");
        jB_Restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RestarActionPerformed(evt);
            }
        });

        jB_Multiplicar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_Multiplicar.setText("*");
        jB_Multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MultiplicarActionPerformed(evt);
            }
        });

        jB_Dividir.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_Dividir.setText("/");
        jB_Dividir.setToolTipText("");
        jB_Dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_DividirActionPerformed(evt);
            }
        });

        jB_Tantoporcien.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB_Tantoporcien.setText("%");
        jB_Tantoporcien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_TantoporcienActionPerformed(evt);
            }
        });

        jB_UnoentreX.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_UnoentreX.setText("/x");
        jB_UnoentreX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_UnoentreXActionPerformed(evt);
            }
        });

        jB_Mas_menos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_Mas_menos.setText("+/-");
        jB_Mas_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Mas_menosActionPerformed(evt);
            }
        });

        jB_Igual.setBackground(new java.awt.Color(102, 102, 102));
        jB_Igual.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jB_Igual.setText("=");
        jB_Igual.setToolTipText("");
        jB_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_IgualActionPerformed(evt);
            }
        });

        jB_guardarTXT.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_guardarTXT.setToolTipText("");
        jB_guardarTXT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jB_guardarTXT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB_guardarTXT.setIconTextGap(3);
        jB_guardarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_guardarTXTActionPerformed(evt);
            }
        });

        jB_3ptos.setText("...");
        jB_3ptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_3ptosActionPerformed(evt);
            }
        });

        jB_cargarTXT.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_cargarTXT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jB_cargarTXT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB_cargarTXT.setIconTextGap(3);
        jB_cargarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cargarTXTActionPerformed(evt);
            }
        });

        jB_Visualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jB_Visualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB_VisualizarMouseEntered(evt);
            }
        });
        jB_Visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_VisualizarActionPerformed(evt);
            }
        });

        jB_Borrar.setPreferredSize(new java.awt.Dimension(50, 50));
        jB_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_BorrarActionPerformed(evt);
            }
        });

        jB_cargarTXT1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jB_cargarTXT1.setText("RESET TICKET");
        jB_cargarTXT1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jB_cargarTXT1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB_cargarTXT1.setIconTextGap(3);
        jB_cargarTXT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cargarTXT1ActionPerformed(evt);
            }
        });

        Archivo.setText("Archivo");
        Archivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Archivo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                ArchivoMenuSelected(evt);
            }
        });
        Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoActionPerformed(evt);
            }
        });
        Archivo.add(jSeparator1);

        Salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        jMenuBar1.add(Archivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_MC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jB_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_MR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_MS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Mmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jB_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_Mas_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Mmas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jB_000, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_Punto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_C, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Restar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_Tantoporcien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jB_UnoentreX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jB_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jB_cargarTXT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTF_Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_cargarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jB_guardarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_Visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jB_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_3ptos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_rutaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_cargarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_guardarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_3ptos)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTF_rutaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_MC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_MR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_MS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Mmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Mas_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Mmas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_000, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Punto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Restar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Tantoporcien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_UnoentreX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jB_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB_cargarTXT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_BackActionPerformed
        //Borrar digitos de uno en uno
        jTF_Pantalla.setText(jTF_Pantalla.getText().substring(0,jTF_Pantalla.getText().length()-1));
    }//GEN-LAST:event_jB_BackActionPerformed

    private void jB_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CEActionPerformed
        /*(Clear Error) Elimina el número mostrado.Se utiliza para cuando se comete un error en el ingreso
        de datos pero sin eliminar todo el cálculo que se encuentra realizando
        */
        jTF_Pantalla.setText("");
    }//GEN-LAST:event_jB_CEActionPerformed

    private void jB_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CActionPerformed
        //(Clear) Elimina todo el cálculo actual
        auxfloat1=0f;
	auxfloat2=0f;
	auxOperacion=' ';
        jTF_Pantalla.setText("");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText()+"\n-----------------------------------\n");
    }//GEN-LAST:event_jB_CActionPerformed

    private void jB_MCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MCActionPerformed
        //(Memory Clear) Elimina cualquier número almacenado en memoria (Teclas: CTRL+L)
        //Limpia la memoria y la etiqueta de memoria
        memoria = 0;
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(pantallaPapel.getText()+ "MC \n"); 
    }//GEN-LAST:event_jB_MCActionPerformed

    private void jB_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_7ActionPerformed
        ///Declaraciones
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "7");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-1));
    }//GEN-LAST:event_jB_7ActionPerformed

    private void jB_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_8ActionPerformed
        //Declaraciones
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "8");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-1));
    }//GEN-LAST:event_jB_8ActionPerformed

    private void jB_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_9ActionPerformed
        //Declaraciones
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "9");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-1));
    }//GEN-LAST:event_jB_9ActionPerformed

    private void jB_MultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MultiplicarActionPerformed
        auxOperacion='*';
        auxfloat1=Float.parseFloat(jTF_Pantalla.getText());
        jTF_Pantalla.setText("");
        pantallaPapel.setText(pantallaPapel.getText()+auxOperacion); 
    }//GEN-LAST:event_jB_MultiplicarActionPerformed

    private void jB_DividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_DividirActionPerformed
        //QUE GENERE ERROR CUANDO SE DIVIDA ENTRE 0
        auxOperacion='/';
        auxfloat1=Float.parseFloat(jTF_Pantalla.getText());
        jTF_Pantalla.setText("");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+auxOperacion);
    }//GEN-LAST:event_jB_DividirActionPerformed

    private void jB_MRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MRActionPerformed
        //(Memory Recall) Recupera el número almacenado en memoria. El número permanece en memoria (Teclas: CTRL+R)
        jTF_Pantalla.setText(memoria + " ");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(pantallaPapel.getText()+ "MR \n"); 
    }//GEN-LAST:event_jB_MRActionPerformed

    private void jB_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_4ActionPerformed
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "4");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-1)); 
    }//GEN-LAST:event_jB_4ActionPerformed

    private void jB_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_5ActionPerformed
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "5");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-1));
    }//GEN-LAST:event_jB_5ActionPerformed

    private void jB_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_6ActionPerformed
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "6");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-1));
    }//GEN-LAST:event_jB_6ActionPerformed

    private void jB_RestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RestarActionPerformed
        auxOperacion='-';
	auxfloat1=Float.parseFloat(jTF_Pantalla.getText());
	jTF_Pantalla.setText("");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+auxOperacion);
    }//GEN-LAST:event_jB_RestarActionPerformed

    private void jB_TantoporcienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_TantoporcienActionPerformed
        auxOperacion='%';
	auxfloat1=Float.parseFloat(jTF_Pantalla.getText());
	jTF_Pantalla.setText("");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+auxOperacion);
    }//GEN-LAST:event_jB_TantoporcienActionPerformed

    private void jB_MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MSActionPerformed
        //(Memory Storage) Almacena en memoria el número mostrado (Teclas: CTRL+M)
        memoria = Float.parseFloat(jTF_Pantalla.getText());
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(pantallaPapel.getText()+ "MS \n"); 
    }//GEN-LAST:event_jB_MSActionPerformed

    private void jB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1ActionPerformed
        //Declaraciones
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "1");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-1));
    }//GEN-LAST:event_jB_1ActionPerformed

    private void jB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2ActionPerformed
        //Declaraciones
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "2");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-1));
    }//GEN-LAST:event_jB_2ActionPerformed

    private void jB_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_3ActionPerformed
        //Declaraciones
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "3");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-1));
    }//GEN-LAST:event_jB_3ActionPerformed

    private void jB_SumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SumarActionPerformed
        auxOperacion='+';
	auxfloat1=Float.parseFloat(jTF_Pantalla.getText());
	jTF_Pantalla.setText("");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+auxOperacion);
    }//GEN-LAST:event_jB_SumarActionPerformed

    private void jB_UnoentreXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_UnoentreXActionPerformed
        auxOperacion='X';
	auxfloat1=Float.parseFloat(jTF_Pantalla.getText());
	jTF_Pantalla.setText("");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+auxOperacion);
    }//GEN-LAST:event_jB_UnoentreXActionPerformed

    private void jB_MmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MmenosActionPerformed
        /*Resta el número mostrado a otro número que se encuentre en memoria pero no muestra la resta 
        de estos números (Teclas: CTRL+Q)
        */
        memoria = memoria - Float.parseFloat(jTF_Pantalla.getText());
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(pantallaPapel.getText()+ "M- \n"); 
    }//GEN-LAST:event_jB_MmenosActionPerformed

    private void jB_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0ActionPerformed
        //Declaraciones
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "0");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-1));
    }//GEN-LAST:event_jB_0ActionPerformed

    private void jB_00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_00ActionPerformed
        //Declaraciones
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "00");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-2));
    }//GEN-LAST:event_jB_00ActionPerformed

    private void jB_Mas_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Mas_menosActionPerformed
        auxOperacion='$';
	auxfloat1=Float.parseFloat(jTF_Pantalla.getText());
	jTF_Pantalla.setText("");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+auxOperacion);
    }//GEN-LAST:event_jB_Mas_menosActionPerformed

    private void jB_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_IgualActionPerformed
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText());
        switch(auxOperacion){
            case '+':
                jTF_Pantalla.setText(" "+(auxfloat1+Float.parseFloat(jTF_Pantalla.getText())));
                auxPantalla= pantallaPapel.getText();
                pantallaPapel.setText(auxPantalla+"\nResultado:"+jTF_Pantalla.getText()+"\n");
                break;
            case '-':
                jTF_Pantalla.setText(" "+(auxfloat1-Float.parseFloat(jTF_Pantalla.getText())));
                auxPantalla= pantallaPapel.getText();
                pantallaPapel.setText(auxPantalla+"\nResultado:"+jTF_Pantalla.getText()+"\n");
                break;    
            case '*':
                jTF_Pantalla.setText(" "+(auxfloat1*Float.parseFloat(jTF_Pantalla.getText())));
                auxPantalla= pantallaPapel.getText();
                pantallaPapel.setText(auxPantalla+"\nResultado:"+jTF_Pantalla.getText()+"\n");
            	break;   
            case '/':
                jTF_Pantalla.setText(" "+(auxfloat1/Float.parseFloat(jTF_Pantalla.getText())));
                auxPantalla= pantallaPapel.getText();
                pantallaPapel.setText(auxPantalla+"\nResultado:"+jTF_Pantalla.getText()+"\n");
 		break;
            case '%':
                jTF_Pantalla.setText(" "+(auxfloat1/100));
                auxPantalla= pantallaPapel.getText();
                pantallaPapel.setText(auxPantalla+"\nResultado:"+jTF_Pantalla.getText()+"\n");
 		break;	  
 	    case 'X':
                jTF_Pantalla.setText(" "+(1/auxfloat1));
                auxPantalla= pantallaPapel.getText();
                pantallaPapel.setText(auxPantalla+"\nResultado:"+jTF_Pantalla.getText()+"\n");
 		break;
            case '$':
 		jTF_Pantalla.setText(" "+(-auxfloat1*Float.parseFloat(jTF_Pantalla.getText())));
                auxPantalla= pantallaPapel.getText();
                pantallaPapel.setText(auxPantalla+"\nResultado:\n"+jTF_Pantalla.getText());
 		break;	 
       
 	}//swicth
    }//GEN-LAST:event_jB_IgualActionPerformed

    private void jB_MmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MmasActionPerformed
        /*Suma el número mostrado a otro número que se encuentre en memoria pero no muestra la suma 
        de estos números (Teclas: CTRL+P)
        */
        memoria = memoria + Float.parseFloat(jTF_Pantalla.getText());
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(pantallaPapel.getText()+ "M+ \n"); 
    }//GEN-LAST:event_jB_MmasActionPerformed

    private void jB_000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_000ActionPerformed
        //Declaraciones
        jTF_Pantalla.setText(jTF_Pantalla.getText() + "000");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText().substring(jTF_Pantalla.getText().length()-3));
    }//GEN-LAST:event_jB_000ActionPerformed

    private void jB_PuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_PuntoActionPerformed
        //Declaraciones
        jTF_Pantalla.setText(jTF_Pantalla.getText() + ".");
        auxPantalla= pantallaPapel.getText();
        pantallaPapel.setText(auxPantalla+jTF_Pantalla.getText());
    }//GEN-LAST:event_jB_PuntoActionPerformed

    private void jB_guardarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_guardarTXTActionPerformed
        //Declaraciones 
       // String str = "src\\papelCalculadora.txt";  //La ruta donde se guardara el archivo
        BufferedWriter bw= null;
        FileWriter fw= null;                
        //***Escritura     
        try { 
            
            File file = new File ("src\\registro\\"+fecha+".txt");  // Creamos la ruta donde se guardara el archivo mas la fecha del dia.
            
            if (!file.exists()) {   //Si NO (!) existe, me lo creas.
            file.createNewFile();  
            }//fin if
            fw= new FileWriter(file.getAbsoluteFile(),true); //Esto es lo que hará que no se machaque lo anterior.
            bw= new BufferedWriter(fw);
            bw.write(pantallaPapel.getText());   //Le decimos que nos escriba lo que haya en el Papel.
            bw.write(8); //retorno de carro 
            bw.write(10); //salto de línea  
            bw.close();//Cierro
 
        } catch(IOException e){ 
            System.out.println("Error E/S: "+e); 
        } finally{              //finalmente...
            try {
                        //Cierra FileWriter y BufferedWriter
            if (bw != null)
                bw.close();
            if (fw != null)
                fw.close();
            }/*fin try*/ catch (IOException ex) {
                ex.printStackTrace();
            } 
            
        }//fin finally
     
    }//GEN-LAST:event_jB_guardarTXTActionPerformed

    private void jTF_PantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_PantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_PantallaActionPerformed

    private void jB_3ptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_3ptosActionPerformed
        File strFile;
        JFileChooser chooser= new JFileChooser();
         int returnVal= chooser.showOpenDialog(chooser);    
        if(returnVal==JFileChooser.APPROVE_OPTION){
            strFile= chooser.getSelectedFile(); 
            jTF_rutaOrigen.setText(strFile.getPath()); //Nos deja en memoria el archivo que hayamos seleccionado. Si despues damos a Leer, nos leera dicho archivo.
        }
    }//GEN-LAST:event_jB_3ptosActionPerformed

    private void jB_cargarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cargarTXTActionPerformed
            String codigo = new String(), path = jTF_rutaOrigen.getText();
            File archivo = new File(path);

            FileReader fr = null;
            BufferedReader entrada = null;
            try {
                fr = new FileReader(path);
                entrada = new BufferedReader(fr);

                while(entrada.ready()){
                    codigo += entrada.readLine()+"\n";
                   
                }
            }catch(IOException e) {
                e.printStackTrace();
            }finally{
                try{                    
                    if(null != fr){   
                        fr.close();     
                    }                  
                }catch (Exception e2){ 
                    e2.printStackTrace();
                }
            }
               pantallaPapel.setText(codigo);
    }//GEN-LAST:event_jB_cargarTXTActionPerformed

    private void ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArchivoActionPerformed

    private void ArchivoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_ArchivoMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_ArchivoMenuSelected

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void jB_VisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_VisualizarActionPerformed
         
        
            Runtime r= Runtime.getRuntime();
                String comando="cmd /c start ..\\CalculadoraPapel\\src\\registro\\"+fecha+".txt";  
		
                Process p=null;
		String linea;

		try{
		
                    p=r.exec(comando);
           
                    InputStream is= p.getInputStream();
                    //Me creas un buffer ya que lee linea a linea y la presentas en pantalla en el Stream abierto. 
                    BufferedReader br= new BufferedReader(new InputStreamReader(is));  

                    //Si la linea no esta vacia me la lees y la imprimes
                    while((linea=br.readLine())!=null){  
        		System.out.println(linea);
                    }
                   
        	br.close();
		}catch(Exception e){
		e.printStackTrace();
		}
        
    }//GEN-LAST:event_jB_VisualizarActionPerformed

    private void jB_VisualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_VisualizarMouseEntered
        
    }//GEN-LAST:event_jB_VisualizarMouseEntered

    private void jB_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_BorrarActionPerformed
        panelBorrado panel= new panelBorrado();
        panel.setVisible(true);
    }//GEN-LAST:event_jB_BorrarActionPerformed

    private void jB_cargarTXT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cargarTXT1ActionPerformed
        pantallaPapel.setText(fecha+""+"\n\n");
        auxfloat1=0f;
	auxfloat2=0f;
	auxOperacion=' ';
        jTF_Pantalla.setText("");
        auxPantalla= pantallaPapel.getText();
    }//GEN-LAST:event_jB_cargarTXT1ActionPerformed
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPapel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPapel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPapel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPapel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraPapel1().setVisible(true);
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JButton jB_0;
    private javax.swing.JButton jB_00;
    private javax.swing.JButton jB_000;
    private javax.swing.JButton jB_1;
    private javax.swing.JButton jB_2;
    private javax.swing.JButton jB_3;
    private javax.swing.JButton jB_3ptos;
    private javax.swing.JButton jB_4;
    private javax.swing.JButton jB_5;
    private javax.swing.JButton jB_6;
    private javax.swing.JButton jB_7;
    private javax.swing.JButton jB_8;
    private javax.swing.JButton jB_9;
    private javax.swing.JButton jB_Back;
    private javax.swing.JButton jB_Borrar;
    private javax.swing.JButton jB_C;
    private javax.swing.JButton jB_CE;
    private javax.swing.JButton jB_Dividir;
    private javax.swing.JButton jB_Igual;
    private javax.swing.JButton jB_MC;
    private javax.swing.JButton jB_MR;
    private javax.swing.JButton jB_MS;
    private javax.swing.JButton jB_Mas_menos;
    private javax.swing.JButton jB_Mmas;
    private javax.swing.JButton jB_Mmenos;
    private javax.swing.JButton jB_Multiplicar;
    private javax.swing.JButton jB_Punto;
    private javax.swing.JButton jB_Restar;
    private javax.swing.JButton jB_Sumar;
    private javax.swing.JButton jB_Tantoporcien;
    private javax.swing.JButton jB_UnoentreX;
    private javax.swing.JButton jB_Visualizar;
    private javax.swing.JButton jB_cargarTXT;
    private javax.swing.JButton jB_cargarTXT1;
    private javax.swing.JButton jB_guardarTXT;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTF_Pantalla;
    private javax.swing.JTextField jTF_rutaOrigen;
    public javax.swing.JTextArea pantallaPapel;
    // End of variables declaration//GEN-END:variables

}//class
